# User config
author: "RealgrapeJuice.DEV"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Front-end Web Development, Reading, Life"
keywords: "HTML, CSS, Javascript, React"
email: "realgrapejuice@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
